/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.SeniorityLevel;
import org.xtext.example.mydsl.myDsl.Worker;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Worker</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.WorkerImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.WorkerImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.WorkerImpl#getSeniority <em>Seniority</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.WorkerImpl#getIsActive <em>Is Active</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WorkerImpl extends MinimalEObjectImpl.Container implements Worker
{
  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSeniority() <em>Seniority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeniority()
   * @generated
   * @ordered
   */
  protected static final SeniorityLevel SENIORITY_EDEFAULT = SeniorityLevel.TRAINEE;

  /**
   * The cached value of the '{@link #getSeniority() <em>Seniority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeniority()
   * @generated
   * @ordered
   */
  protected SeniorityLevel seniority = SENIORITY_EDEFAULT;

  /**
   * The default value of the '{@link #getIsActive() <em>Is Active</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIsActive()
   * @generated
   * @ordered
   */
  protected static final org.xtext.example.mydsl.myDsl.Boolean IS_ACTIVE_EDEFAULT = org.xtext.example.mydsl.myDsl.Boolean.TRUE;

  /**
   * The cached value of the '{@link #getIsActive() <em>Is Active</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIsActive()
   * @generated
   * @ordered
   */
  protected org.xtext.example.mydsl.myDsl.Boolean isActive = IS_ACTIVE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorkerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.WORKER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WORKER__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WORKER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SeniorityLevel getSeniority()
  {
    return seniority;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeniority(SeniorityLevel newSeniority)
  {
    SeniorityLevel oldSeniority = seniority;
    seniority = newSeniority == null ? SENIORITY_EDEFAULT : newSeniority;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WORKER__SENIORITY, oldSeniority, seniority));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.example.mydsl.myDsl.Boolean getIsActive()
  {
    return isActive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsActive(org.xtext.example.mydsl.myDsl.Boolean newIsActive)
  {
    org.xtext.example.mydsl.myDsl.Boolean oldIsActive = isActive;
    isActive = newIsActive == null ? IS_ACTIVE_EDEFAULT : newIsActive;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.WORKER__IS_ACTIVE, oldIsActive, isActive));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.WORKER__ID:
        return getId();
      case MyDslPackage.WORKER__NAME:
        return getName();
      case MyDslPackage.WORKER__SENIORITY:
        return getSeniority();
      case MyDslPackage.WORKER__IS_ACTIVE:
        return getIsActive();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.WORKER__ID:
        setId((String)newValue);
        return;
      case MyDslPackage.WORKER__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.WORKER__SENIORITY:
        setSeniority((SeniorityLevel)newValue);
        return;
      case MyDslPackage.WORKER__IS_ACTIVE:
        setIsActive((org.xtext.example.mydsl.myDsl.Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.WORKER__ID:
        setId(ID_EDEFAULT);
        return;
      case MyDslPackage.WORKER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.WORKER__SENIORITY:
        setSeniority(SENIORITY_EDEFAULT);
        return;
      case MyDslPackage.WORKER__IS_ACTIVE:
        setIsActive(IS_ACTIVE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.WORKER__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case MyDslPackage.WORKER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.WORKER__SENIORITY:
        return seniority != SENIORITY_EDEFAULT;
      case MyDslPackage.WORKER__IS_ACTIVE:
        return isActive != IS_ACTIVE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(", name: ");
    result.append(name);
    result.append(", seniority: ");
    result.append(seniority);
    result.append(", isActive: ");
    result.append(isActive);
    result.append(')');
    return result.toString();
  }

} //WorkerImpl
