/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Difficulty Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DifficultyCondition#getDifficulty <em>Difficulty</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDifficultyCondition()
 * @model
 * @generated
 */
public interface DifficultyCondition extends Condition
{
  /**
   * Returns the value of the '<em><b>Difficulty</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.Difficulty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Difficulty</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Difficulty
   * @see #setDifficulty(Difficulty)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDifficultyCondition_Difficulty()
   * @model
   * @generated
   */
  Difficulty getDifficulty();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DifficultyCondition#getDifficulty <em>Difficulty</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Difficulty</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Difficulty
   * @see #getDifficulty()
   * @generated
   */
  void setDifficulty(Difficulty value);

} // DifficultyCondition
