/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Workers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WORKERS = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TASKS = 1;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__RULES = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WorkerImpl <em>Worker</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WorkerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWorker()
   * @generated
   */
  int WORKER = 1;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKER__ID = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKER__NAME = 1;

  /**
   * The feature id for the '<em><b>Seniority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKER__SENIORITY = 2;

  /**
   * The feature id for the '<em><b>Is Active</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKER__IS_ACTIVE = 3;

  /**
   * The number of structural features of the '<em>Worker</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TaskImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTask()
   * @generated
   */
  int TASK = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Difficulty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DIFFICULTY = 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DURATION = 2;

  /**
   * The feature id for the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__START = 3;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RuleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRule()
   * @generated
   */
  int RULE = 3;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Assign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ASSIGN = 1;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TIMEImpl <em>TIME</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TIMEImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTIME()
   * @generated
   */
  int TIME = 4;

  /**
   * The feature id for the '<em><b>Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__HOURS = 0;

  /**
   * The feature id for the '<em><b>Minutes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__MINUTES = 1;

  /**
   * The number of structural features of the '<em>TIME</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 5;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ShiftConditionImpl <em>Shift Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ShiftConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getShiftCondition()
   * @generated
   */
  int SHIFT_CONDITION = 6;

  /**
   * The feature id for the '<em><b>Shift</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIFT_CONDITION__SHIFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Shift Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHIFT_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ComparisonImpl <em>Comparison</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ComparisonImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 7;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__OPERATOR = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__DURATION = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comparison</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DifficultyConditionImpl <em>Difficulty Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DifficultyConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDifficultyCondition()
   * @generated
   */
  int DIFFICULTY_CONDITION = 8;

  /**
   * The feature id for the '<em><b>Difficulty</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONDITION__DIFFICULTY = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Difficulty Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OrConditionImpl <em>Or Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OrConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOrCondition()
   * @generated
   */
  int OR_CONDITION = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AndConditionImpl <em>And Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AndConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAndCondition()
   * @generated
   */
  int AND_CONDITION = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION__LEFT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION__RIGHT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.PrimaryConditionImpl <em>Primary Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.PrimaryConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPrimaryCondition()
   * @generated
   */
  int PRIMARY_CONDITION = 11;

  /**
   * The feature id for the '<em><b>Inner</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_CONDITION__INNER = CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Primary Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.SeniorityLevel <em>Seniority Level</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.SeniorityLevel
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSeniorityLevel()
   * @generated
   */
  int SENIORITY_LEVEL = 12;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.Difficulty <em>Difficulty</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.Difficulty
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDifficulty()
   * @generated
   */
  int DIFFICULTY = 13;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.Boolean <em>Boolean</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.Boolean
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 14;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.Shift <em>Shift</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.Shift
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getShift()
   * @generated
   */
  int SHIFT = 15;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getWorkers <em>Workers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Workers</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getWorkers()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Workers();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getTasks()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tasks();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getRules()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Rules();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Worker <em>Worker</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Worker</em>'.
   * @see org.xtext.example.mydsl.myDsl.Worker
   * @generated
   */
  EClass getWorker();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Worker#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.myDsl.Worker#getId()
   * @see #getWorker()
   * @generated
   */
  EAttribute getWorker_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Worker#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Worker#getName()
   * @see #getWorker()
   * @generated
   */
  EAttribute getWorker_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Worker#getSeniority <em>Seniority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Seniority</em>'.
   * @see org.xtext.example.mydsl.myDsl.Worker#getSeniority()
   * @see #getWorker()
   * @generated
   */
  EAttribute getWorker_Seniority();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Worker#getIsActive <em>Is Active</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Active</em>'.
   * @see org.xtext.example.mydsl.myDsl.Worker#getIsActive()
   * @see #getWorker()
   * @generated
   */
  EAttribute getWorker_IsActive();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Task#getDifficulty <em>Difficulty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Difficulty</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task#getDifficulty()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Difficulty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Task#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task#getDuration()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Duration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Task#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Start</em>'.
   * @see org.xtext.example.mydsl.myDsl.Task#getStart()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Start();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Rule#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rule#getCondition()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Condition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Rule#getAssign <em>Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Assign</em>'.
   * @see org.xtext.example.mydsl.myDsl.Rule#getAssign()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Assign();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.TIME <em>TIME</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>TIME</em>'.
   * @see org.xtext.example.mydsl.myDsl.TIME
   * @generated
   */
  EClass getTIME();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.TIME#getHours <em>Hours</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hours</em>'.
   * @see org.xtext.example.mydsl.myDsl.TIME#getHours()
   * @see #getTIME()
   * @generated
   */
  EAttribute getTIME_Hours();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.TIME#getMinutes <em>Minutes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minutes</em>'.
   * @see org.xtext.example.mydsl.myDsl.TIME#getMinutes()
   * @see #getTIME()
   * @generated
   */
  EAttribute getTIME_Minutes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ShiftCondition <em>Shift Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shift Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.ShiftCondition
   * @generated
   */
  EClass getShiftCondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ShiftCondition#getShift <em>Shift</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Shift</em>'.
   * @see org.xtext.example.mydsl.myDsl.ShiftCondition#getShift()
   * @see #getShiftCondition()
   * @generated
   */
  EAttribute getShiftCondition_Shift();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison</em>'.
   * @see org.xtext.example.mydsl.myDsl.Comparison
   * @generated
   */
  EClass getComparison();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Comparison#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see org.xtext.example.mydsl.myDsl.Comparison#getOperator()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Operator();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Comparison#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.mydsl.myDsl.Comparison#getDuration()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Duration();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DifficultyCondition <em>Difficulty Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Difficulty Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.DifficultyCondition
   * @generated
   */
  EClass getDifficultyCondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.DifficultyCondition#getDifficulty <em>Difficulty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Difficulty</em>'.
   * @see org.xtext.example.mydsl.myDsl.DifficultyCondition#getDifficulty()
   * @see #getDifficultyCondition()
   * @generated
   */
  EAttribute getDifficultyCondition_Difficulty();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.OrCondition <em>Or Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.OrCondition
   * @generated
   */
  EClass getOrCondition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.OrCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.myDsl.OrCondition#getLeft()
   * @see #getOrCondition()
   * @generated
   */
  EReference getOrCondition_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.OrCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.myDsl.OrCondition#getRight()
   * @see #getOrCondition()
   * @generated
   */
  EReference getOrCondition_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AndCondition <em>And Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.AndCondition
   * @generated
   */
  EClass getAndCondition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.AndCondition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.myDsl.AndCondition#getLeft()
   * @see #getAndCondition()
   * @generated
   */
  EReference getAndCondition_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.AndCondition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.myDsl.AndCondition#getRight()
   * @see #getAndCondition()
   * @generated
   */
  EReference getAndCondition_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.PrimaryCondition <em>Primary Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primary Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.PrimaryCondition
   * @generated
   */
  EClass getPrimaryCondition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.PrimaryCondition#getInner <em>Inner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inner</em>'.
   * @see org.xtext.example.mydsl.myDsl.PrimaryCondition#getInner()
   * @see #getPrimaryCondition()
   * @generated
   */
  EReference getPrimaryCondition_Inner();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.SeniorityLevel <em>Seniority Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Seniority Level</em>'.
   * @see org.xtext.example.mydsl.myDsl.SeniorityLevel
   * @generated
   */
  EEnum getSeniorityLevel();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.Difficulty <em>Difficulty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Difficulty</em>'.
   * @see org.xtext.example.mydsl.myDsl.Difficulty
   * @generated
   */
  EEnum getDifficulty();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Boolean</em>'.
   * @see org.xtext.example.mydsl.myDsl.Boolean
   * @generated
   */
  EEnum getBoolean();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.Shift <em>Shift</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Shift</em>'.
   * @see org.xtext.example.mydsl.myDsl.Shift
   * @generated
   */
  EEnum getShift();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Workers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__WORKERS = eINSTANCE.getModel_Workers();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TASKS = eINSTANCE.getModel_Tasks();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__RULES = eINSTANCE.getModel_Rules();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WorkerImpl <em>Worker</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WorkerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWorker()
     * @generated
     */
    EClass WORKER = eINSTANCE.getWorker();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKER__ID = eINSTANCE.getWorker_Id();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKER__NAME = eINSTANCE.getWorker_Name();

    /**
     * The meta object literal for the '<em><b>Seniority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKER__SENIORITY = eINSTANCE.getWorker_Seniority();

    /**
     * The meta object literal for the '<em><b>Is Active</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKER__IS_ACTIVE = eINSTANCE.getWorker_IsActive();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TaskImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Difficulty</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DIFFICULTY = eINSTANCE.getTask_Difficulty();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DURATION = eINSTANCE.getTask_Duration();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__START = eINSTANCE.getTask_Start();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RuleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITION = eINSTANCE.getRule_Condition();

    /**
     * The meta object literal for the '<em><b>Assign</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__ASSIGN = eINSTANCE.getRule_Assign();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TIMEImpl <em>TIME</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TIMEImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTIME()
     * @generated
     */
    EClass TIME = eINSTANCE.getTIME();

    /**
     * The meta object literal for the '<em><b>Hours</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__HOURS = eINSTANCE.getTIME_Hours();

    /**
     * The meta object literal for the '<em><b>Minutes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__MINUTES = eINSTANCE.getTIME_Minutes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ShiftConditionImpl <em>Shift Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ShiftConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getShiftCondition()
     * @generated
     */
    EClass SHIFT_CONDITION = eINSTANCE.getShiftCondition();

    /**
     * The meta object literal for the '<em><b>Shift</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SHIFT_CONDITION__SHIFT = eINSTANCE.getShiftCondition_Shift();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ComparisonImpl <em>Comparison</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ComparisonImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComparison()
     * @generated
     */
    EClass COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__OPERATOR = eINSTANCE.getComparison_Operator();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__DURATION = eINSTANCE.getComparison_Duration();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DifficultyConditionImpl <em>Difficulty Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DifficultyConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDifficultyCondition()
     * @generated
     */
    EClass DIFFICULTY_CONDITION = eINSTANCE.getDifficultyCondition();

    /**
     * The meta object literal for the '<em><b>Difficulty</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIFFICULTY_CONDITION__DIFFICULTY = eINSTANCE.getDifficultyCondition_Difficulty();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OrConditionImpl <em>Or Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OrConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOrCondition()
     * @generated
     */
    EClass OR_CONDITION = eINSTANCE.getOrCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_CONDITION__LEFT = eINSTANCE.getOrCondition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_CONDITION__RIGHT = eINSTANCE.getOrCondition_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AndConditionImpl <em>And Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AndConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAndCondition()
     * @generated
     */
    EClass AND_CONDITION = eINSTANCE.getAndCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_CONDITION__LEFT = eINSTANCE.getAndCondition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_CONDITION__RIGHT = eINSTANCE.getAndCondition_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.PrimaryConditionImpl <em>Primary Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.PrimaryConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getPrimaryCondition()
     * @generated
     */
    EClass PRIMARY_CONDITION = eINSTANCE.getPrimaryCondition();

    /**
     * The meta object literal for the '<em><b>Inner</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIMARY_CONDITION__INNER = eINSTANCE.getPrimaryCondition_Inner();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.SeniorityLevel <em>Seniority Level</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.SeniorityLevel
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSeniorityLevel()
     * @generated
     */
    EEnum SENIORITY_LEVEL = eINSTANCE.getSeniorityLevel();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.Difficulty <em>Difficulty</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.Difficulty
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDifficulty()
     * @generated
     */
    EEnum DIFFICULTY = eINSTANCE.getDifficulty();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.Boolean <em>Boolean</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.Boolean
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBoolean()
     * @generated
     */
    EEnum BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.Shift <em>Shift</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.Shift
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getShift()
     * @generated
     */
    EEnum SHIFT = eINSTANCE.getShift();

  }

} //MyDslPackage
