/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PrimaryCondition#getInner <em>Inner</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryCondition()
 * @model
 * @generated
 */
public interface PrimaryCondition extends Condition
{
  /**
   * Returns the value of the '<em><b>Inner</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inner</em>' containment reference.
   * @see #setInner(Condition)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryCondition_Inner()
   * @model containment="true"
   * @generated
   */
  Condition getInner();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PrimaryCondition#getInner <em>Inner</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inner</em>' containment reference.
   * @see #getInner()
   * @generated
   */
  void setInner(Condition value);

} // PrimaryCondition
