/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TIME</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TIME#getHours <em>Hours</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TIME#getMinutes <em>Minutes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTIME()
 * @model
 * @generated
 */
public interface TIME extends EObject
{
  /**
   * Returns the value of the '<em><b>Hours</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hours</em>' attribute.
   * @see #setHours(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTIME_Hours()
   * @model
   * @generated
   */
  int getHours();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TIME#getHours <em>Hours</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hours</em>' attribute.
   * @see #getHours()
   * @generated
   */
  void setHours(int value);

  /**
   * Returns the value of the '<em><b>Minutes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minutes</em>' attribute.
   * @see #setMinutes(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTIME_Minutes()
   * @model
   * @generated
   */
  int getMinutes();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TIME#getMinutes <em>Minutes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minutes</em>' attribute.
   * @see #getMinutes()
   * @generated
   */
  void setMinutes(int value);

} // TIME
